"""Thin wrapper around the Anthropic Messages API.

Synchronous by design: the caller blocks until Claude returns. That suits this
tool's workload (a small batch of responses generated by hand). If it ever needs
to run a real batch, the generation call should move behind a task queue.
"""

import logging
import os

import anthropic

logger = logging.getLogger(__name__)

MAX_TOKENS = 16000
# generous, but bounded -- a hung upstream shouldn't pin a worker for the SDK's
# 10 minute default
REQUEST_TIMEOUT_SECONDS = 180.0


class GenerationError(Exception):
    """A generation attempt that produced no usable response.

    `status_code` is what the API layer should hand back to the caller, so the
    HTTP mapping lives next to the failure that caused it.
    """

    def __init__(self, message: str, status_code: int = 502):
        super().__init__(message)
        self.message = message
        self.status_code = status_code


def _client() -> anthropic.Anthropic:
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise GenerationError(
            "ANTHROPIC_API_KEY is not set. Put it in .env at the repo root and "
            "run `docker compose up -d --force-recreate backend`.",
            status_code=503,
        )
    return anthropic.Anthropic(api_key=api_key, timeout=REQUEST_TIMEOUT_SECONDS)


def generate(prompt_text: str, model: str) -> str:
    """Send one prompt to Claude and return the text of the reply.

    Raises GenerationError for anything that doesn't yield usable text.
    """
    client = _client()

    try:
        message = client.messages.create(
            model=model,
            max_tokens=MAX_TOKENS,
            messages=[{"role": "user", "content": prompt_text}],
        )
    except anthropic.BadRequestError as e:
        raise GenerationError(f"Anthropic rejected the request: {e.message}", 400) from e
    except anthropic.NotFoundError as e:
        raise GenerationError(f"Unknown model {model!r}.", 400) from e
    except anthropic.AuthenticationError as e:
        raise GenerationError("ANTHROPIC_API_KEY was rejected by Anthropic.", 502) from e
    except anthropic.PermissionDeniedError as e:
        raise GenerationError(f"This API key cannot access {model!r}.", 502) from e
    except anthropic.RateLimitError as e:
        raise GenerationError("Rate limited by Anthropic. Try again shortly.", 429) from e
    except anthropic.APIConnectionError as e:
        raise GenerationError("Could not reach the Anthropic API.", 504) from e
    except anthropic.APIStatusError as e:
        raise GenerationError(f"Anthropic returned {e.status_code}.", 502) from e

    logger.info("generation ok: model=%s request_id=%s", model, message._request_id)

    # a refusal comes back as HTTP 200, so stop_reason has to be checked before
    # the content is read
    if message.stop_reason == "refusal":
        detail = getattr(message.stop_details, "category", None)
        raise GenerationError(
            f"Claude declined to answer this prompt (category: {detail}).", 422
        )

    if message.stop_reason == "max_tokens":
        logger.warning(
            "response hit the %s token cap and is truncated", MAX_TOKENS
        )

    # content is a list of blocks; thinking blocks are present by default on
    # Opus 5 and must not end up in the stored response
    text = "".join(b.text for b in message.content if b.type == "text").strip()
    if not text:
        raise GenerationError("Claude returned no text content.", 502)

    return text
